### ISSUE TITLE
Missing wheel for 3.1.1

### ISSUE THREAD

**Issue by caramdache** [valdergallo/data-importer#102]
I have the issue with `data-importer 3.1.1`. It can be seen by `pip3 search`, but not by `pip3 install` which only sees `data-importer 3.0.2`. I tried the `-no-cache` and `-no-cache-dir` and `rm -rf ~/.cache/pip` and upgraded `pip`, but still the issue is here.

I thought the issue was with `pip`, but it seems there is a configuration issue with `data-importer`:

https://github.com/pypa/warehouse/issues/3962#issuecomment-614556938

Could you please have a look at it?

**Comment by valdergallo** [comment]
I made a new version 3.1.5
