### ISSUE TITLE
Deprecation warning for Django 1.9

### ISSUE THREAD

**Issue by minrock** [valdergallo/data-importer#66]
/..../.virtualenvs/..../lib/python2.7/site-packages/data_importer/models.py:14: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.

**Comment by valdergallo** [comment]
Yeaah I have one pull request fixing this. I need create one new version
and send to pypi
Em 25/08/2015 11:24, "Luis Moncaris" <notifications@github.com> escreveu:

**Comment by valdergallo** [comment]
https://github.com/valdergallo/data-importer/pull/65
