### ISSUE TITLE
XML Importer does not call process_row method

### ISSUE THREAD

**Issue by koztay** [valdergallo/data-importer#87]
I am overriding process row method for XLS and XLSX importers in order to save data on a row to multiple models. But when I want to override it for XML files, then process_row method never called. So, I cannot use it for XML files.

**Comment by valdergallo** [comment]
@koztay stranger buddy .... because the `process_row` is on `BaseImporter`, all importer must have the `process_row` .  The XML reader is using one Root -> childs (nothing sooooo smart). Maybe you have some problem in your XML.

Look my example in tests
``` 
<encspot>
  <file>
   <Name>some filename.mp3</Name>
   <Encoder>Gogo (after 3.0)</Encoder>
   <Bitrate>131</Bitrate>
  </file>
  <file>
   <Name>another filename.mp3</Name>
   <Encoder>iTunes</Encoder>
   <Bitrate>128</Bitrate>
  </file>
</encspot>
```

And my importer
```
class TestXML(XMLImporter):
    root = 'file'  # <file>
    fields = ['name', 'encoder', 'bitrate']

```

**Comment by valdergallo** [comment]
@koztay  could you post your process_row method :D

**Comment by koztay** [comment]
@valdergallo thank you very much. I just could find a chance to try your importer and sample XML file, and the result was process_row method called successfully. I think the problem is, there was no fields setting in my importer, and the reason was that I am planning to get the fields dynamically. Because I have several files from several vendors for my model and every vendor has different fields in their XML file (my importer is a bit custom importer). After I put fields setting there as manually it has been called without any problem. So, now it is cleared for me and I will keep continue to develop my custom importer.
