### ISSUE TITLE
Enhance example or provide more docs

### ISSUE THREAD

**Issue by eugenio** [valdergallo/data-importer#91]
Could you provide more detailed and complete example case use for django in particular? The provided ones are a bit cryptic for those new to it.
Alternatively can you tell me how to get docs on the source?

Bests,
Eugenio.

**Comment by valdergallo** [comment]
Wow more docs to use with Django ... 
Did you checked the (https://django-data-importer.readthedocs.io/en/latest/)
And (https://github.com/valdergallo/data-importer/tree/master/example)

**Comment by eugenio** [comment]
thanks, I could not find the docs on readthedocs! Stupid me! I guess I can close the issue for now.

**Comment by eugenio** [comment]
sorry for bothering you, but I'm not able to save data to the database. This is my view method for the importing:
` def uploadfile(request):
	if request.method == 'POST':
			form = FileUploadForm(request.POST, request.FILES)
			extra_context = {'title':'Create Form Data Importer', 'template_file':'myfile.xml'}
			importer = xmlmdls.advantage_list_model
			importer.post_save_all_lines(importer)
			return HttpResponseRedirect(reverse(index))
	else:
			print('topolino')
			form = FileUploadForm()
			return render(request , 'uploadfile.html' , {'form': form})`

and this is my importer model:

` class advantage_list_model(XMLImporter):
	class Meta:
		raise_errors = True
		model = advantage_list_model`

while this is an example file to be parsed:

`<?xml version="1.0" encoding="US-ASCII" ?>
<advantage_list unique_id="hv8ssnqd:14n9tuefwh7nz" version="1">
	<advantage_container version="2" open="yes">
         .........
	</advantage_container>
</advantage_list>`

Could you please tell me what is wrong? The code executes without errors but no data is saved to the database

**Comment by valdergallo** [comment]
"model = advantage_list_model"

Model should be one Django Model table. 
"advantage_list_model"  can't be saved by the "importer.save(importer)"
